### ISSUE TITLE
[Suggestion] Leap cooldown

### ISSUE THREAD

**Issue by milkev** [qxeii/nox-renoxed#15]
It would be cool if the leap had a cooldown (with a config)
Currently, once in range, zombies just infinitely pounce at you, resulting in them just dancing around you endlessly which can make them very difficult to hit or run away from. It would feel a lot more natural/fair if there was a 2-3 second cooldown.

**Comment by qxeii** [comment]
I've added a pouncing cooldown config for creepers/zombies. Will be included in the next update.
