### ISSUE TITLE
Curseforge?

### ISSUE THREAD

**Issue by Killercrab432** [qxeii/nox-renoxed#23]
Any chance you can add this mod to curse?, i really wanna use it in my modpack but wont be able to publish it if its not on curse

**Comment by qxeii** [comment]
Just created a page on CurseForge. It might take a while to get approved but hopefully it helps!

**Comment by Killercrab432** [comment]
@qxeii i would appreciate it if you could add the 1.20.1 version of the mod to the curseforge page aswell, especially since its the most popular modding version
