### ISSUE TITLE
Crash occuring on loading world  (nox$setPounceCooldown(J)V is abstract)

### ISSUE THREAD

**Issue by Killercrab432** [qxeii/nox-renoxed#26]
https://pastebin.com/AEBgtQHK

**Comment by Killercrab432** [comment]
Fabric 0.15.7 mc version 1.20.1 any idea on whats causing it?

**Comment by Killercrab432** [comment]
Looks like an issue exclusive to the curseforge version of the mod, doesnt occur on modrinth

**Comment by qxeii** [comment]
> Looks like an issue exclusive to the curseforge version of the mod, doesnt occur on modrinth

Are you using any other mods with it? If not then it could be an issue with the jar i uploaded for it.

**Comment by Killercrab432** [comment]
i used the same mod list when testing both the curseforge and modrinth version if thats what your asking, i am using other mods the list can be seen on the crash report

**Comment by qxeii** [comment]
> i used the same mod list when testing both the curseforge and modrinth version if thats what your asking, i am using other mods the list can be seen on the crash report

i've uploaded a jar that should be fixed to curseforge, try that

**Comment by Killercrab432** [comment]
issue doesnt seem to be occuring anymore, thanks!
